version: '3'
services:
  tauri-app:  # コンテナ名を"tauri-app"に変更
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /path/to/your/app:/app
    environment:
      - ANDROID_HOME=/path/to/android/sdk
      - NDK_HOME=/path/to/android/ndk
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PATH=$PATH:$HOME/.cargo/bin
    ports:
      - "3000:3000"  # ポートマッピングを追加
    # その他の設定を追加する場合、ここに記述
